version: '3.8'

services:
  # Single Node Running All Services
  polymesh-all-in-one:
    image: polymeshassociation/polymesh:latest-develop-distroless
    container_name: polymesh-all-in-one
    environment:
      - NODE_KEY=your_node_key_here
    ports:
      - "30333:30333"   # P2P port
      - "9933:9933"     # RPC port
      - "9944:9944"     # WebSocket port
    volumes:
      - ./polymesh-data:/polymesh-data
    command: >
      --base-path /polymesh-data
      --chain private
      --name "Polymesh All-In-One Node"
      --rpc-cors all
      --rpc-methods Unsafe
      --ws-external
      --rpc-external
      --validator
      --pruning archive
      --unsafe-rpc-external
      --unsafe-ws-external

networks:
  default:
    name: polymesh-net
    driver: bridge
